//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiteApp_v1._2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.ModelConfiguration.Conventions;

    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

            modelBuilder.Entity<Employee>()
                .HasMany(c => c.Attributes).WithMany(i => i.Employees)
                .Map(t => t.MapLeftKey("EMPATTR_EmployeeID")
                    .MapRightKey("EMPATTR_AttributeID")
                    .ToTable("EmployeeAttribute"));

            throw new UnintentionalCodeFirstException();
        }

      



        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }

       
    }
}
